name: qiime2-2023.2
channels:
  - rapidsai
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - entrez-direct=16.2
  - bioconductor-mia=1.6.0
  - clang=14.0.6
  - ld64_osx-64=609
  - libglib=2.74.1
  - liblapack=3.9.0
  - matplotlib=3.6.0
  - r-vctrs=0.5.2
  - threadpoolctl=3.1.0
  - r-tidyr=1.3.0
  - interface_meta=1.3.0
  - r-e1071=1.7_13
  - jinja2=3.1.2
  - bioconductor-biomformat=1.26.0
  - r-htmltools=0.5.4
  - libidn2=2.3.4
  - make=4.3
  - q2-diversity-lib=2023.2.0
  - xorg-libice=1.0.10
  - perl-parent=0.241
  - r-processx=3.8.0
  - q2-sample-classifier=2023.2.0
  - r-readxl=1.4.2
  - r-r6=2.5.1
  - icu=70.1
  - r-cvxr=1.0_11
  - r-rematch=1.0.1
  - libopenblas=0.3.21
  - r-cpp11=0.4.3
  - r-formula=1.2_5
  - fonts-conda-ecosystem=1
  - q2-diversity=2023.2.0
  - r-fnn=1.1.3.1
  - pango=1.50.13
  - pycparser=2.21
  - jupyter_events=0.6.3
  - r-bibtex=0.5.1
  - r-hwriter=1.3.2.1
  - urllib3=1.26.14
  - gneiss=0.4.6
  - r-optparse=1.7.3
  - anyio=3.6.2
  - yq=3.1.1
  - bioconductor-genomeinfodbdata=1.2.9
  - altair=4.2.2
  - r-gridextra=2.3
  - nbconvert-core=7.2.9
  - click=8.1.3
  - r-energy=1.7_11
  - markupsafe=2.1.2
  - bleach=6.0.0
  - bioconductor-biocsingular=1.14.0
  - nose=1.3.7
  - r-progress=1.2.2
  - r-statmod=1.5.0
  - openjpeg=2.5.0
  - clangxx_osx-64=14.0.6
  - bowtie2=2.5.1
  - r-igraph=1.4.1
  - r-lubridate=1.9.2
  - c-ares=1.18.1
  - libssh2=1.10.0
  - r-data.table=1.14.8
  - font-ttf-source-code-pro=2.038
  - brotlipy=0.7.0
  - font-ttf-ubuntu=0.83
  - q2-types=2023.2.0
  - r-dqrng=0.3.0
  - q2-quality-control=2023.2.0
  - pluggy=1.0.0
  - mafft=7.515
  - ipywidgets=8.0.4
  - r-viridis=0.6.2
  - libbrotlidec=1.0.9
  - r-cli=3.6.0
  - bioconductor-iranges=2.32.0
  - libiconv=1.17
  - bioconductor-scater=1.26.0
  - r-iterators=1.0.14
  - importlib_resources=5.12.0
  - cctools_osx-64=973.0.1
  - r-expm=0.999_7
  - backports=1.0
  - libllvm11=11.1.0
  - r-ade4=1.7_22
  - python-fastjsonschema=2.16.3
  - q2-feature-classifier=2023.2.0
  - q2-composition=2023.2.0
  - sniffio=1.3.0
  - mistune=2.0.5
  - bioconductor-shortread=1.56.0
  - perl-json=4.10
  - future=0.18.3
  - r-xtable=1.8_4
  - r-vipor=0.4.5
  - requests=2.28.2
  - scipy=1.8.1
  - r-fastmap=1.1.1
  - wcwidth=0.2.6
  - jq=1.6
  - importlib_metadata=4.8.3
  - r-sitmo=2.0.2
  - r-blob=1.2.3
  - perl-encode=3.19
  - importlib-metadata=4.8.3
  - perl-pathtools=3.75
  - q2cli=2023.2.0
  - gsl=2.7
  - bioconductor-biocparallel=1.32.5
  - ipykernel=6.21.2
  - r-viridislite=0.4.1
  - appnope=0.1.3
  - pickleshare=0.7.5
  - r-cachem=1.0.7
  - r-desctools=0.99.48
  - perl-compress-raw-zlib=2.202
  - bioconductor-treeio=1.22.0
  - atpublic=3.0.1
  - perl-list-moreutils=0.430
  - r-backports=1.4.1
  - python=3.8.16
  - isa-l=2.30.0
  - bioconductor-rhdf5filters=1.10.0
  - pexpect=4.8.0
  - q2galaxy=2023.2.0
  - astor=0.8.1
  - setuptools=67.4.0
  - comm=0.1.2
  - wget=1.20.3
  - parso=0.8.3
  - kiwisolver=1.4.4
  - libwebp-base=1.2.4
  - ipython=8.10.0
  - r-plyr=1.8.8
  - _r-mutex=1.0.1
  - pytest=7.2.1
  - wrapt=1.15.0
  - r-mime=0.12
  - bioconductor-scaledmatrix=1.6.0
  - jupyterlab_pygments=0.2.2
  - r-nlme=3.1_162
  - r-rcurl=1.98_1.10
  - beautifulsoup4=4.11.2
  - r-sys=3.4.1
  - scikit-bio=0.5.7
  - xmltodict=0.13.0
  - r-sp=1.6_0
  - r-plogr=0.2.0
  - websocket-client=1.5.1
  - liblapacke=3.9.0
  - bioconductor-ancombc=2.0.1
  - r-emmeans=1.8.4_1
  - perl=5.32.1
  - matplotlib-base=3.6.0
  - r-tibble=3.1.8
  - cython=0.29.33
  - r-base=4.2.2
  - exceptiongroup=1.1.0
  - iqtree=2.2.0.3
  - emperor=1.0.3
  - nlopt=2.7.1
  - r-jsonlite=1.8.4
  - r-clipr=0.8.0
  - libgfortran5=11.3.0
  - qiime2=2023.2.0
  - pcre2=10.40
  - r-png=0.1_8
  - lerc=4.0.0
  - r-dplyr=1.1.0
  - perl-archive-tar=2.40
  - r-foreign=0.8_84
  - r-rematch2=2.1.2
  - jedi=0.18.2
  - r-bit=4.0.5
  - expat=2.5.0
  - r-rvest=1.0.3
  - r-ggrastr=1.0.1
  - krb5=1.20.1
  - r-lme4=1.1_31
  - pbzip2=1.1.13
  - r-modelr=0.1.10
  - r-interp=1.1_3
  - r-openssl=2.0.5
  - r-hms=1.1.2
  - bioconductor-decontam=1.18.0
  - bioconductor-biostrings=2.66.0
  - pigz=2.6
  - platformdirs=3.0.0
  - r-base64enc=0.1_3
  - perl-types-serialiser=1.01
  - argon2-cffi-bindings=21.2.0
  - perl-extutils-makemaker=7.66
  - bwidget=1.9.14
  - r-highr=0.10
  - openssl=3.0.8
  - jupyterlab_widgets=3.0.5
  - ncurses=6.3
  - cutadapt=4.2
  - r-doparallel=1.0.17
  - toolz=0.12.0
  - r-rsvd=1.0.5
  - dendropy=4.5.2
  - r-sass=0.4.5
  - q2-feature-table=2023.2.0
  - xorg-libxau=1.0.9
  - compiler-rt=14.0.6
  - zstd=1.5.2
  - openjdk=17.0.3
  - debugpy=1.6.6
  - r-checkmate=2.1.0
  - llvmlite=0.39.1
  - r-forcats=1.0.0
  - clang-14=14.0.6
  - r-rstudioapi=0.14
  - nbconvert-pandoc=7.2.9
  - r-evaluate=0.20
  - r-uuid=1.1_0
  - tqdm=4.64.1
  - r-tzdb=0.3.0
  - dnaio=0.10.0
  - typing-extensions=4.4.0
  - r-rcpp=1.0.10
  - libcblas=3.9.0
  - r-rbibutils=2.2.13
  - readline=8.1.2
  - bioconductor-matrixgenerics=1.10.0
  - nest-asyncio=1.5.6
  - webencodings=0.5.1
  - r-latticeextra=0.6_30
  - r-withr=2.5.0
  - libedit=3.1.20191231
  - bioconductor-data-packages=20230202
  - pkgutil-resolve-name=1.3.10
  - r-readr=2.1.4
  - perl-io-zlib=1.14
  - r-foreach=1.5.2
  - libtiff=4.4.0
  - clang_osx-64=14.0.6
  - psutil=5.9.4
  - r-gbrd=0.4_11
  - raxml=8.2.12
  - r-reshape2=1.4.4
  - xyzservices=2023.2.0
  - r-googledrive=2.0.0
  - gfortran_osx-64=11.3.0
  - libxml2=2.10.3
  - r-yaml=2.3.7
  - r-dbi=1.1.3
  - networkx=3.0
  - r-rsqlite=2.2.20
  - r-gargle=1.3.0
  - r-estimability=1.4.1
  - r-tidyselect=1.2.0
  - bioconductor-multiassayexperiment=1.24.0
  - bioconductor-rhtslib=2.0.0
  - libcxx=15.0.7
  - perl-carp=1.50
  - python_abi=3.8
  - r-askpass=1.1
  - r-bslib=0.4.2
  - r-futile.options=1.0.1
  - notebook=6.5.2
  - tomli=2.0.1
  - cffi=1.15.1
  - q2-gneiss=2023.2.0
  - r-deldir=1.0_6
  - prometheus_client=0.16.0
  - glpk=5.0
  - r-farver=2.1.1
  - r-rcolorbrewer=1.1_3
  - nbclassic=0.5.2
  - q2-deblur=2023.2.0
  - tktable=2.10
  - r-broom=1.0.3
  - r-hmisc=4.8_0
  - libdeflate=1.13
  - r-rcppml=0.3.7
  - toml=0.10.2
  - libzlib=1.2.13
  - r-minqa=1.2.5
  - cycler=0.11.0
  - munkres=1.1.4
  - xopen=1.7.0
  - pynndescent=0.5.8
  - r-curl=4.3.3
  - r-registry=0.5_1
  - r-rcppparallel=5.1.6
  - jupyter_client=8.0.3
  - vsearch=2.22.1
  - bzip2=1.0.8
  - r-isoband=0.2.7
  - r-nnet=7.3_18
  - libblas=3.9.0
  - bioconductor-rsamtools=2.14.0
  - r-codetools=0.2_19
  - r-fansi=1.0.4
  - r-rcppeigen=0.3.3.9.3
  - r-timechange=0.2.0
  - scikit-learn=0.24.1
  - biom-format=2.1.12
  - fontconfig=2.14.2
  - zipp=3.15.0
  - r-lambda.r=1.2.4
  - bioconductor-genomeinfodb=1.34.8
  - bioconductor-multtest=2.54.0
  - r-munsell=0.5.0
  - r-gld=2.6.6
  - q2-mystery-stew=2023.2.0
  - libxslt=1.1.37
  - q2-metadata=2023.2.0
  - compiler-rt_osx-64=14.0.6
  - xorg-kbproto=1.0.7
  - rfc3986-validator=0.1.1
  - r-rtsne=0.16
  - r-pkgconfig=2.0.3
  - sigtool=0.1.3
  - r-bh=1.81.0_1
  - flit-core=3.8.0
  - perl-exporter-tiny=1.002002
  - natsort=8.3.0
  - r-knitr=1.42
  - r-uwot=0.1.14
  - perl-common-sense=3.75
  - seaborn=0.12.2
  - r-selectr=0.4_2
  - r-jpeg=0.1_10
  - bioconductor-xvector=0.38.0
  - bioconductor-genomicranges=1.50.0
  - brotli-bin=1.0.9
  - lz4=4.3.2
  - bioconductor-treesummarizedexperiment=2.6.0
  - r-dorng=1.8.6
  - r-tidyverse=1.3.2
  - sepp=4.3.10
  - freetype=2.12.1
  - iniconfig=2.0.0
  - gfortran_impl_osx-64=11.3.0
  - ptyprocess=0.7.0
  - r-ggplot2=3.4.1
  - r-yulab.utils=0.0.6
  - tbb=2021.8.0
  - send2trash=1.8.0
  - gmp=6.2.1
  - samtools=1.16.1
  - numba=0.56.4
  - llvm-openmp=15.0.7
  - bioconductor-phyloseq=1.42.0
  - bioconductor-biocbaseutils=1.0.0
  - xz=5.2.6
  - bioconductor-beachmat=2.14.0
  - sortmerna=2.0
  - attrs=22.2.0
  - q2-demux=2023.2.0
  - ca-certificates=2022.12.7
  - r-lazyeval=0.2.2
  - r-xml2=1.3.3
  - q2-emperor=2023.2.0
  - r-digest=0.6.31
  - xorg-libsm=1.2.3
  - fribidi=1.0.10
  - r-haven=2.5.1
  - r-numderiv=2016.8_1.1
  - r-assertthat=0.2.1
  - perl-compress-raw-bzip2=2.201
  - bioconductor-decipher=2.26.0
  - fonts-conda-forge=1
  - python-json-logger=2.0.7
  - hdf5=1.10.6
  - r-ggrepel=0.9.3
  - joblib=1.2.0
  - r-class=7.3_21
  - harfbuzz=6.0.0
  - python-dateutil=2.8.2
  - llvm-tools=14.0.6
  - libpng=1.6.39
  - r-generics=0.1.3
  - zlib=1.2.13
  - pygments=2.14.0
  - r-gtable=0.3.1
  - q2-fragment-insertion=2023.2.0
  - jupyter_server_terminals=0.4.4
  - packaging=23.0
  - r-mass=7.3_58.2
  - six=1.16.0
  - entrypoints=0.4
  - q2-longitudinal=2023.2.0
  - r-proxy=0.4_27
  - matplotlib-inline=0.1.6
  - bioconductor-zlibbioc=1.44.0
  - font-ttf-inconsolata=3.000
  - numpy=1.23.5
  - jupyter_server=2.3.0
  - r-ps=1.7.2
  - r-rngtools=1.5.2
  - r-rmarkdown=2.20
  - ijson=3.2.0.post0
  - pyzmq=25.0.0
  - r-rcpphnsw=0.4.1
  - asttokens=2.2.1
  - rfc3339-validator=0.1.4
  - q2templates=2023.2.0
  - r-matrix=1.5_3
  - tk=8.6.12
  - nbconvert=7.2.9
  - python-isal=1.1.0
  - unifrac=1.1.1
  - bioconductor-rhdf5=2.42.0
  - lockfile=0.12.2
  - r-exact=3.2
  - r-snow=0.4_4
  - zstandard=0.19.0
  - r-jquerylib=0.1.4
  - decorator=4.4.2
  - statsmodels=0.13.5
  - cairo=1.16.0
  - r-bitops=1.0_7
  - jsonschema=4.17.3
  - formulaic=0.5.2
  - q2-taxa=2023.2.0
  - r-fs=1.6.1
  - unicodedata2=15.0.0
  - brotli=1.0.9
  - pip=23.0.1
  - fasttree=2.1.11
  - pandocfilters=1.5.0
  - perl-list-moreutils-xs=0.430
  - pyrsistent=0.19.3
  - bioconductor-delayedmatrixstats=1.20.0
  - typing_extensions=4.4.0
  - r-ggbeeswarm=0.7.1
  - traitlets=5.9.0
  - r-httr=1.4.5
  - bokeh=3.0.3
  - nbclient=0.7.2
  - perl-exporter=5.74
  - clangxx=14.0.6
  - r-rdpack=2.4
  - nbformat=5.7.3
  - bioconductor-s4vectors=0.36.0
  - xorg-libxt=1.2.1
  - lxml=4.9.2
  - isl=0.25
  - r-prettyunits=1.1.1
  - pixman=0.40.0
  - deblur=1.1.1
  - xorg-libxdmcp=1.1.3
  - certifi=2022.12.7
  - notebook-shim=0.2.2
  - pandoc=2.19.2
  - tzlocal=2.1
  - bioconductor-sparsematrixstats=1.10.0
  - r-gmp=0.7_1
  - pure_eval=0.2.2
  - bioconductor-dirichletmultinomial=1.40.0
  - r-pillar=1.8.1
  - backcall=0.2.0
  - flufl.lock=7.1
  - h5py=2.10.0
  - libclang-cpp14=14.0.6
  - pytz=2022.7.1
  - q2-quality-filter=2023.2.0
  - r-googlesheets4=1.0.1
  - bioconductor-singlecellexperiment=1.20.0
  - bioconductor-biocgenerics=0.44.0
  - q2-dada2=2023.2.0
  - pyparsing=3.0.9
  - r-xfun=0.37
  - r-rspectra=0.16_1
  - argon2-cffi=21.3.0
  - mpfr=4.1.0
  - libllvm14=14.0.6
  - libunistring=0.9.10
  - r-textshaping=0.3.6
  - libnghttp2=1.51.0
  - q2-cutadapt=2023.2.0
  - r-permute=0.9_7
  - lz4-c=1.9.4
  - r-reprex=2.0.2
  - q2-alignment=2023.2.0
  - contourpy=1.0.7
  - r-lmertest=3.1_3
  - r-rmpfr=0.9_1
  - r-tinytex=0.44
  - backports.functools_lru_cache=1.6.4
  - r-mvtnorm=1.1_3
  - jupyter_core=5.2.0
  - r-lattice=0.20_45
  - r-rcppprogress=0.4.2
  - r-dtplyr=1.3.0
  - ipython_genutils=0.2.0
  - libsodium=1.0.18
  - r-rlang=1.0.6
  - blast=2.12.0
  - oniguruma=6.9.8
  - fastcluster=1.2.6
  - r-dbplyr=2.3.1
  - r-vroom=1.6.1
  - msgpack-python=1.0.4
  - colorama=0.4.6
  - pcre=8.45
  - argcomplete=2.0.0
  - r-ids=1.0.1
  - r-labeling=0.4.2
  - r-tidytree=0.4.2
  - seaborn-base=0.12.2
  - tapi=1100.0.11
  - pillow=9.2.0
  - yaml=0.2.5
  - r-nloptr=2.0.3
  - cachecontrol=0.12.11
  - r-ellipsis=0.3.2
  - r-getopt=1.20.3
  - libbrotlicommon=1.0.9
  - fonttools=4.38.0
  - libbrotlienc=1.0.9
  - bioconductor-summarizedexperiment=1.28.0
  - mpc=1.3.1
  - r-ecosolver=0.5.4
  - libgfortran-devel_osx-64=11.3.0
  - cryptography=39.0.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - gettext=0.21.1
  - widgetsnbextension=4.0.5
  - r-glue=1.6.2
  - tinycss2=1.2.1
  - r-vegan=2.6_4
  - r-ape=5.7
  - r-crayon=1.5.2
  - htslib=1.16
  - hmmer=3.1b2
  - pyopenssl=23.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - libffi=3.4.2
  - r-scales=1.2.1
  - r-lifecycle=1.0.3
  - pyyaml=6.0
  - libcurl=7.88.1
  - bioconductor-dada2=1.26.0
  - umap-learn=0.5.3
  - r-matrixstats=0.63.0
  - r-irlba=2.3.5.1
  - r-rpart=4.1.19
  - graphlib-backport=1.0.3
  - r-rootsolve=1.8.2.3
  - graphite2=1.3.13
  - r-boot=1.3_28.1
  - r-pixmap=0.4_12
  - r-htmlwidgets=1.6.1
  - libxcb=1.13
  - r-bit64=4.0.5
  - r-pheatmap=1.0.12
  - r-pkgmaker=0.32.8
  - bibtexparser=1.4.0
  - r-cairo=1.6_0
  - r-stringr=1.5.0
  - cached_property=1.5.2
  - r-osqp=0.6.0.8
  - q2-vsearch=2023.2.0
  - r-beeswarm=0.4.0
  - r-memoise=2.0.1
  - hdmedians=0.14.2
  - zeromq=4.3.4
  - r-survival=3.5_3
  - bioconductor-delayedarray=0.24.0
  - executing=1.2.0
  - iow=1.0.5
  - r-cellranger=1.1.0
  - r-colorspace=2.1_0
  - bioconductor-biobase=2.58.0
  - r-systemfonts=1.0.4
  - patsy=0.5.3
  - lcms2=2.14
  - r-callr=3.7.3
  - r-ragg=1.2.4
  - defusedxml=0.7.1
  - curl=7.88.1
  - terminado=0.17.1
  - r-gsl=2.1_8
  - r-utf8=1.2.3
  - stack_data=0.6.2
  - tornado=6.2
  - xorg-xproto=7.0.31
  - perl-storable=3.15
  - libsqlite=3.40.0
  - r-rappdirs=0.3.3
  - bioconductor-biocneighbors=1.16.0
  - r-cluster=2.1.4
  - perl-scalar-list-utils=1.63
  - bioconductor-scuttle=1.8.0
  - prompt-toolkit=3.0.36
  - q2-phylogeny=2023.2.0
  - r-mgcv=1.8_41
  - bioconductor-rhdf5lib=1.20.0
  - r-acepack=1.4.1
  - perl-json-xs=2.34
  - xorg-libx11=1.7.2
  - soupsieve=2.3.2.post1
  - wheel=0.38.4
  - r-scs=3.0_1
  - perl-io-compress=2.201
  - r-stringi=1.7.12
  - r-futile.logger=1.4.3
  - idna=3.4
  - r-lmom=2.9
  - pandas=1.5.3
  - r-formatr=1.14
  - jpeg=9e
  - r-purrr=1.0.1
  - r-magrittr=2.0.3
  - r-rcppannoy=0.0.20
  - libev=4.33
  - dill=0.3.6
  - r-frictionless=1.0.2
  - r-htmltable=2.4.1
  - libgfortran=5.0.0
  - unifrac-binaries=1.1.1
  - bioconductor-genomicalignments=1.34.0
  - charset-normalizer=2.1.1
